site_name: 'Документация Scorocode'
pages:
    - 'Scorocode': 
        - 'Общие сведения': 'index.md'
        - 'Начало работы': 'main/main1.md'
        - 'Личный кабинет': 'main/main2.md'
        - 'Работа с приложением': 'app/app.md'
        - 'Аналитика приложения': 'app/app1.md'
        - 'Данные приложения': 'app/app2.md'
        - 'Индексы': 'app/app3.md'
        - 'Триггеры': 'app/app4.md'
        - 'Серверный код приложения': 'app/app5.md'
        - 'Настройки приложения': 'app/app6.md'
    - 'HTTP API': 
        - 'Работа с приложением': 'httpapi/appapi.md'
        - 'Пользователи': 'httpapi/httpapi1.md'
        - 'Данные': 'httpapi/httpapi2.md'
        - 'Файлы': 'httpapi/httpapi3.md'
        - 'Сообщения': 'httpapi/httpapi4.md'
        - 'Скрипты': 'httpapi/httpapi5.md'
        - 'Статистика': 'httpapi/httpapi6.md'
    - 'JavaScript SDK':
        - 'JavaScript SDK': 'JS/javascript.md'
        - 'Scorocode': 'JS/Scorocode.md'
        - 'Scorocode.Object': 'JS/Scorocode.Object.md'
        - 'Scorocode.Query': 'JS/Scorocode.Query.md'
        - 'Scorocode.UpdateOps': 'JS/Scorocode.UpdateOps.md'
        - 'Scorocode.User': 'JS/Scorocode.User.md'
        - 'Scorocode.Messenger': 'JS/Scorocode.Messenger.md'
        - 'Scorocode.CloudCode': 'JS/Scorocode.CloudCode.md'
        - 'Scorocode.WebSocket': 'JS/Scorocode.Websocket.md'
    - 'SWIFT SDK (iOs, Mac OS)':
        - 'SWIFT SDK': 'SWIFT/SWIFT.md'
        - 'SC': 'SWIFT/SC.md'
        - 'SCValue': 'SWIFT/SCValue.md'
        - 'SCObject': 'SWIFT/SCObject.md'
        - 'SCQuery': 'SWIFT/SCQuery.md'
        - 'SCUpdate': 'SWIFT/SCUpdate.md'
        - 'SCUser': 'SWIFT/SCUser.md'
        - 'SCMessage': 'SWIFT/SCMessage.md'
        - 'SCScript': 'SWIFT/SCScript.md'
        - 'WebSocket': 'SWIFT/WebSocket.md'
    - 'Java SDK (Android)':
        - 'Java SDK': 'Java/Java.md'
        - 'Класс ScorocodeSDK': 'Java/ScorocodeSDK.md'
        - 'Класс Document': 'Java/Document.md'
        - 'Класс Update': 'Java/Update.md'
        - 'Класс User': 'Java/User.md'
        - 'Класс Query': 'Java/Query.md'
        - 'Класс Script': 'Java/Script.md'
        - 'Класс Message': 'Java/Message.md'
        - 'Класс WebSocket': 'Java/WebSocket.md'
    - 'Примеры приложений':
        - 'Склад (Android)': 'Java/Storehouse.md'
theme_dir: 'material'
extra:
  logo: 'logo.png'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  i18n:
    prev: 'Предыдущий раздел'
    next: 'Следующий раздел'
  palette:
    primary: 'blue'
    accent: 'light blue'
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)